---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 5
  rounds:
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 1050
    - 1100
    - 1150
    - 1200
    - 1250
    - 1300
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1050
    - type: fixed-rate
      opts:
        tps: 1100
    - type: fixed-rate
      opts:
        tps: 1150
    - type: fixed-rate
      opts:
        tps: 1200
    - type: fixed-rate
      opts:
        tps: 1250
    - type: fixed-rate
      opts:
        tps: 1300
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
